language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install '.[dev]'
script:
- pytest
deploy:
  provider: pypi
  username: petioptrv
  password:
    secure: z4sCOp2814F5oSWt6TC0IJTkw8bJorbMf/dUj1rt1BHij7PFVXEx0jLhEuNBwjb4CuU33UjeCrUTUCiPMnPJFMW5IY2AG28IBqbR8aZ+nwfcolG/+VpAOyozl2RtklISL8yhYOwjjp3q8NG7ssNbRsCra0d++ObdLWTWmk67x0fKve2XIpalW9dyIZig8vJmd/8oNBCyLBqMgMef+rdmYAptqIZYYEIu261dS5Le8qLUIIXSXmdAclAK53/0fXO0aZvHhXcTnWEM5fovApuiOhS75va1LWmmniCayPbZH35lc+DMxB9lJL3AmoqvZR/+B0OsGxT4dxbUpYXyXatOzAZf3osJ7FeNknob3KHL0xO0W3xsm1Bfdu78FJkBHsBOqCiVKc+nvpY0/6Zg3QLYqIH1DOHCE+vuIQthDxK3uqlH3Xb2MZiz9eDT93ZCjMIqPZ7uHWpeGwlChRfpOG+tvJ+m544ABx9ugfAQ4kSOr6a3Rb34uRiDXNpadlmOcS2ove6b8pm8Y8pK5bhM3hsIedeMnnZ4PvIibCEmnQWgXebDpoMixOYUQ+MC9Vutoz1Jvu/cX0+s7Dfz7JcRG08nVi4rlf6Bqvd1G+2D25TVrW6f6FTmcyl1kCAFg80eSfzo5N6CTSSljuwccgfCeKm0cLDh7v/n4m1Wgb62GgJFNsY=
  on:
    tags: true
    branch: master
